"""Host-side alembic environment.

Three things differ from atrium's ``backend/alembic/env.py``:

1. ``target_metadata`` points at the host's ``HostBase.metadata`` so
   autogenerate only sees host tables. Atrium's tables are managed by
   atrium's own chain — never touch them from here.
2. ``version_table`` is set to ``alembic_version_app`` so the two
   chains track their heads independently. They share the database
   but never collide on a revision.
3. ``process_revision_directives`` is wired to
   ``emit_host_foreign_keys`` so columns declared with
   ``HostForeignKey()`` get their cross-base ``ForeignKeyConstraint``
   emitted into autogenerated migrations.
"""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context
from app.host_sdk.alembic import emit_host_foreign_keys
from app.settings import get_settings

# ``HostBase`` is the metadata target; importing it from
# ``atrium_ddns.models`` also runs the package's ``__init__``, which
# registers every model class on ``HostBase.metadata`` before
# autogenerate inspects it.
from atrium_ddns.models import HostBase

VERSION_TABLE = "alembic_version_app"

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

if not config.get_main_option("sqlalchemy.url") or config.get_main_option(
    "sqlalchemy.url"
).startswith("driver://"):
    config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = HostBase.metadata


def _include_object(obj, name, type_, reflected, compare_to):
    """Filter atrium tables out of autogenerate.

    Both atrium and the host write to the same MySQL database. With
    ``target_metadata = HostBase.metadata`` alembic sees atrium's
    tables as "in the DB but not in the model" and would emit
    ``drop_table`` ops for every one of them on the first
    autogenerate. Only emit ops for tables (and child objects) that
    live in ``HostBase.metadata``.
    """
    if type_ == "table":
        return name in target_metadata.tables
    if reflected:
        parent = getattr(obj, "table", None)
        if parent is not None and parent.name not in target_metadata.tables:
            return False
    return True


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table=VERSION_TABLE,
        include_object=_include_object,
        process_revision_directives=emit_host_foreign_keys,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        version_table=VERSION_TABLE,
        compare_type=True,
        render_as_batch=False,
        include_object=_include_object,
        process_revision_directives=emit_host_foreign_keys,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
