"""ddns core schema — domains, devices, hostnames, backends, events

Revision ID: 0002_ddns_core
Revises: 0001_init
Create Date: 2026-08-15

Autogenerated from ``atrium_ddns.models`` and then hand-finished. Four
things are worth knowing before editing it.

**Why 0002 and not an edit to 0001.** ``0001_init`` is on ``master``,
merged, and stamped in every database that has ever run
``make migrate`` — the deploy host's among them. Amending it in place
would create these tables on a fresh database and silently create none
of them anywhere alembic already reads ``0001_init`` from
``alembic_version_app``. Local green, deployed nothing.

**The four foreign keys to ``users.id`` are not in the models.** They
are declared with ``HostForeignKey`` — a marker on ``Column.info``, not
a SQLAlchemy ``ForeignKey`` — because a column-level FK across two
``MetaData`` objects fails at mapper-init. ``emit_host_foreign_keys``
in ``alembic/env.py`` turns the markers into the four
``sa.ForeignKeyConstraint([...], ['users.id'], ...)`` lines below at
autogenerate time. They are real database constraints; only the ORM
does not know about them.

**Every FK to ``users.id`` is on an ``Integer`` column.** ``users.id``
is MySQL ``int``. A ``bigint`` child fails ``ADD FOREIGN KEY`` with
errno 150 and an error text that never mentions the width.

**``updated_at`` carries its ``ON UPDATE`` in raw DDL.** SQLAlchemy's
``server_onupdate=`` is documentation and emits nothing — the
scaffolded ``atrium_ddns_state.updated_at`` uses it and the resulting
column has no ``ON UPDATE`` clause, so it has never changed after
insert. Spelling it into ``server_default`` is the only form that
reaches the database. ``alembic`` does not compare server defaults
(``compare_server_default`` is off), so this produces no autogenerate
noise.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.auth.rbac_seed import seed_permissions_sync
from app.host_sdk.crypto import SecretBlob
from sqlalchemy.dialects import mysql

revision: str = "0002_ddns_core"
down_revision: str | None = "0001_init"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# DEFAULT + ON UPDATE in one expression. See the module docstring.
_TOUCHED = sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)")
_CREATED = sa.text("CURRENT_TIMESTAMP(6)")

# Frozen at this revision on purpose: a migration is a statement about
# what happened, and importing ``atrium_ddns.models.PERMISSIONS`` here
# would make this revision's behaviour change every time that constant
# does. The live check that the two agree is
# ``tests/test_host_models.py::test_seeded_permissions_match_the_model_constant``,
# which reads the database rather than either file.
PERMISSIONS = (
    "atrium_ddns.domain.manage",
    "atrium_ddns.device.manage",
    "atrium_ddns.hostname.manage",
    "atrium_ddns.admin",
    "atrium_ddns.events.read.all",
)

GRANTS = {
    "user": [
        "atrium_ddns.domain.manage",
        "atrium_ddns.device.manage",
        "atrium_ddns.hostname.manage",
    ],
    "admin": list(PERMISSIONS),
}


def upgrade() -> None:
    # --- devices ------------------------------------------------------ #
    # The DDNS credential and the unit a hostname belongs to. The secret
    # is a *hash* (argon2id for new rows, bcrypt for rows carried over
    # from the old service) and deliberately not a SecretBlob: it is only
    # ever compared, never handed back.
    op.create_table(
        "ddns_device",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_ip_v4", sa.String(length=15), nullable=True),
        sa.Column("last_ip_v6", sa.String(length=45), nullable=True),
        sa.Column("last_user_agent", sa.String(length=255), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=_TOUCHED,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_ddns_device_user_name"),
        sa.UniqueConstraint("username", name="uq_ddns_device_username"),
    )
    op.create_index(
        op.f("ix_ddns_device_user_id"), "ddns_device", ["user_id"], unique=False
    )

    # --- domains ------------------------------------------------------ #
    # Zone name is unique **globally** — DNS is global. Ownership is the
    # multi-tenancy change; uniqueness is not.
    op.create_table(
        "ddns_domain",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=_TOUCHED,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_ddns_domain_name"),
    )
    op.create_index(
        op.f("ix_ddns_domain_user_id"), "ddns_domain", ["user_id"], unique=False
    )

    # --- provider bindings + per-user encrypted credentials ----------- #
    # `credentials_ct` holds the ciphertext; the plaintext is reached
    # through the `DomainBackend.credentials` descriptor after an
    # `await unlock_user_secrets(session, row.user_id)`. `user_id` is
    # denormalised from the domain because the descriptor reads the
    # owner off *this* row.
    op.create_table(
        "ddns_domain_backend",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("backend_type", sa.String(length=64), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        # `SecretBlob()` alone compiles to `BLOB` (64 KB) — see the note
        # on `DomainBackend.credentials_ct`. The variant is what makes
        # the column the MEDIUMBLOB the primitive documents.
        sa.Column(
            "credentials_ct",
            SecretBlob().with_variant(mysql.MEDIUMBLOB(), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=_TOUCHED,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["ddns_domain.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "domain_id", "backend_type", name="uq_ddns_domain_backend_type"
        ),
    )
    op.create_index(
        op.f("ix_ddns_domain_backend_domain_id"),
        "ddns_domain_backend",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ddns_domain_backend_user_id"),
        "ddns_domain_backend",
        ["user_id"],
        unique=False,
    )

    # --- hostnames ---------------------------------------------------- #
    # `device_id` is nullable and SET NULL: a name can exist before it is
    # assigned, and deleting a device must not delete the names it was
    # maintaining.
    op.create_table(
        "ddns_hostname",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("last_ip_v4", sa.String(length=15), nullable=True),
        sa.Column("last_ip_v6", sa.String(length=45), nullable=True),
        sa.Column("last_updated_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("dns_ip_v4", sa.String(length=15), nullable=True),
        sa.Column("dns_ip_v6", sa.String(length=45), nullable=True),
        sa.Column("dns_checked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("dns_check_error", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=_TOUCHED,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["ddns_device.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["ddns_domain.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_ddns_hostname_name"),
    )
    op.create_index(
        op.f("ix_ddns_hostname_device_id"),
        "ddns_hostname",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        "ix_ddns_hostname_dns_checked_at",
        "ddns_hostname",
        ["dns_checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ddns_hostname_domain_id"),
        "ddns_hostname",
        ["domain_id"],
        unique=False,
    )

    # --- per-device rate-limit window --------------------------------- #
    # Legacy `RateLimitEvent`, re-keyed to the device (plan §2). No
    # writer until #16; declared here because #16 has `abuse` in its
    # acceptance criteria and no migration in its declared scope.
    op.create_table(
        "ddns_rate_limit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["ddns_device.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ddns_rate_limit_event_created_at",
        "ddns_rate_limit_event",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ddns_rate_limit_event_device_created",
        "ddns_rate_limit_event",
        ["device_id", "created_at"],
        unique=False,
    )

    # --- the DNS update log ------------------------------------------- #
    # Four SET NULL foreign keys *and* four denormalised name columns.
    # The keys are what the filters index on; the strings are what keeps
    # an entry readable after the row it describes is gone, which is
    # exactly when it gets read.
    op.create_table(
        "ddns_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=_CREATED,
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.BigInteger(), nullable=True),
        sa.Column("domain_id", sa.BigInteger(), nullable=True),
        sa.Column("hostname_id", sa.BigInteger(), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("domain_name", sa.String(length=255), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("response_code", sa.String(length=16), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["ddns_device.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["ddns_domain.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["hostname_id"], ["ddns_hostname.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ddns_event_client_ip", "ddns_event", ["client_ip"], unique=False
    )
    op.create_index(
        "ix_ddns_event_created_at", "ddns_event", ["created_at"], unique=False
    )
    op.create_index(
        "ix_ddns_event_device_created",
        "ddns_event",
        ["device_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ddns_event_domain_id"), "ddns_event", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_ddns_event_hostname_id"),
        "ddns_event",
        ["hostname_id"],
        unique=False,
    )
    op.create_index(
        "ix_ddns_event_user_created",
        "ddns_event",
        ["user_id", "created_at"],
        unique=False,
    )

    # --- permissions --------------------------------------------------- #
    # Atrium auto-grants every seeded permission to `super_admin`, so it
    # is absent from GRANTS on purpose (an entry for it is skipped).
    # Unknown role codes warn and skip rather than raising.
    seed_permissions_sync(op.get_bind(), PERMISSIONS, grants=GRANTS)


def downgrade() -> None:
    # Permissions are intentionally left in place, matching 0001's
    # convention: they are cheap to keep, removing them would orphan any
    # UI still referencing the code, and `seed_permissions_sync` is
    # INSERT IGNORE, so a re-upgrade over the leftovers is a no-op
    # rather than a duplicate-key failure. That is what makes
    # upgrade -> downgrade -> upgrade clean.
    #
    # **Tables only, no `drop_index`.** Autogenerate wrote the mirror of
    # `upgrade()` — every index dropped, then the table — and it does
    # not run: MySQL refuses `DROP INDEX ix_ddns_event_user_created`
    # with errno 1553, because InnoDB elected that compound index as
    # the supporting index for the `user_id` foreign key and will not
    # leave a constraint unindexed. (That election is the reason there
    # is no separate `ix_ddns_event_user_id`: `(user_id, created_at)`
    # serves both.) `DROP TABLE` takes the indexes with it, so the
    # explicit drops were redundant as well as fatal.
    #
    # Order is child-before-parent. `ddns_event` references all four of
    # the others, `ddns_hostname` and `ddns_rate_limit_event` reference
    # `ddns_device`, and `ddns_domain_backend` and `ddns_hostname`
    # reference `ddns_domain`.
    op.drop_table("ddns_event")
    op.drop_table("ddns_rate_limit_event")
    op.drop_table("ddns_hostname")
    op.drop_table("ddns_domain_backend")
    op.drop_table("ddns_domain")
    op.drop_table("ddns_device")
